#!/usr/bin/env python3
"""Generates build/corpus/corpus_generated.h from tests/corpus/captures/**/*.yaml.

The host test build is a plain g++ invocation with gtest — no YAML parser, and runtime file
loading would add CWD fragility. So the corpus is rendered into a `constexpr`-friendly C++
header on every build. The output is a build artifact (git-ignored, lives under build/), not
committed: the YAML captures are the single source of truth, so there is nothing to drift out
of sync with and nothing to keep in the repo besides the captures themselves.

Output is deterministic (captures sorted by `id`, stable formatting, no timestamps) as a
matter of hygiene, not because anything diffs against it.

Run automatically by `make unit-test` before compiling; safe to run directly for local
inspection. Dependency: PyYAML.
"""

import sys
from pathlib import Path

import yaml

from protolib import parse_hex

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CAPTURES_DIR = REPO_ROOT / "tests" / "corpus" / "captures"
OUTPUT_PATH = REPO_ROOT / "build" / "corpus" / "corpus_generated.h"

BANNER = "// GENERATED by scripts/corpus/build.py — DO NOT EDIT. Source: tests/corpus/captures/"

KEY_MODE_ENUM = {"corpus": "KeyMode::CORPUS", "unknown": "KeyMode::UNKNOWN"}
EXCHANGE_KIND_ENUM = {
    "direct": "ExchangeKind::DIRECT",
    "authenticated_command": "ExchangeKind::AUTHENTICATED_COMMAND",
    "pairing": "ExchangeKind::PAIRING",
    "oneway": "ExchangeKind::ONEWAY",
    "status_poll": "ExchangeKind::STATUS_POLL",
}
EXCHANGE_OUTCOME_ENUM = {
    "success": "ExchangeOutcome::SUCCESS",
    "timeout": "ExchangeOutcome::TIMEOUT",
    "failure": "ExchangeOutcome::FAILURE",
}

# `classification` expectations name a value from one of the four decisions::*Disposition
# enums in components/home_io_control/hub_decisions.h. Names are bare (not enum-qualified) to
# match the design vocabulary (REQUIRE_AUTH, ACCEPT, IGNORE_UNRELATED, ...), except where two
# enums give the same name a *different* numeric value: PairingDiscoveryDisposition::ACCEPT is
# 2, while ExchangeFinalResponseDisposition::ACCEPT and PairingKeyChallengeDisposition::ACCEPT
# are both 1 — that one case is disambiguated as DISCOVERY_ACCEPT. Every value here is pinned
# against the real enum by a static_assert in tests/corpus_classification_test.cpp, so a reorder
# of hub_decisions.h breaks the build instead of silently mis-scoring a capture.
CLASSIFICATION_ENUM = {
    "IGNORE_UNRELATED": 0,  # ExchangeFirstResponseDisposition / ExchangeFinalResponseDisposition
    "COMPLETE_DIRECT": 1,  # ExchangeFirstResponseDisposition
    "REQUIRE_AUTH": 2,  # ExchangeFirstResponseDisposition
    "ACCEPT": 1,  # ExchangeFinalResponseDisposition / PairingKeyChallengeDisposition
    "NO_RESPONSE": 0,  # PairingDiscoveryDisposition
    "INVALID": 1,  # PairingDiscoveryDisposition
    "DISCOVERY_ACCEPT": 2,  # PairingDiscoveryDisposition::ACCEPT (disambiguated, see above)
    "IGNORE": 0,  # PairingKeyChallengeDisposition
}


def c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_byte_array(name: str, data: bytes) -> str:
    byte_list = ", ".join(f"0x{b:02X}" for b in data)
    return f"inline constexpr uint8_t {name}[] = {{{byte_list}}};"


def render_frame(capture_slug: str, index: int, frame: dict, expect_frame: dict) -> "tuple[str, str]":
    """Returns (byte-array declaration, CorpusFrame initializer)."""
    raw = parse_hex(frame["hex"])
    array_name = f"{capture_slug}_frame{index}_bytes"
    array_decl = render_byte_array(array_name, raw)

    tx = "true" if frame["dir"] == "tx" else "false"
    has_t_ms = "t_ms" in frame
    t_ms = frame.get("t_ms", 0)
    freq_hz = frame.get("freq", 0)
    crc_present = "true" if frame["crc"] == "present" else "false"

    has_cmd = "cmd" in expect_frame
    cmd = expect_frame.get("cmd", 0)

    # start/end/protocol are one combined has_flags expectation in the generated struct (they
    # describe the same CTRL0 byte), so a capture must specify all three together or none —
    # specifying only one would silently assert false for the other two without a human having
    # verified that, contradicting the "expectations are human-verified" rule in the README.
    flag_keys_present = {"start", "end", "protocol"} & expect_frame.keys()
    if flag_keys_present and flag_keys_present != {"start", "end", "protocol"}:
        raise SystemExit(
            f"error: {capture_slug} frame[{index}]: partial flag expectation {sorted(flag_keys_present)} — "
            "specify all of start/end/protocol together, or omit all three"
        )
    has_flags = bool(flag_keys_present)
    start = "true" if expect_frame.get("start", False) else "false"
    end = "true" if expect_frame.get("end", False) else "false"
    oneway = "true" if expect_frame.get("protocol") == "1w" else "false"

    # `classification` expectations map a symbolic decisions:: enum name (e.g. "REQUIRE_AUTH")
    # to its numeric value via CLASSIFICATION_ENUM above.
    has_classification = "classification" in expect_frame
    classification_expr = "0"
    if has_classification:
        name = expect_frame["classification"]
        if name not in CLASSIFICATION_ENUM:
            raise SystemExit(
                f"error: {capture_slug} frame[{index}]: expect.frames[{index}].classification {name!r} is not "
                f"one of {sorted(CLASSIFICATION_ENUM)}"
            )
        classification_expr = str(CLASSIFICATION_ENUM[name])

    has_hmac_valid = "hmac_valid" in expect_frame
    hmac_valid = "true" if expect_frame.get("hmac_valid", False) else "false"

    initializer = (
        f"    {{{tx}, {'true' if has_t_ms else 'false'}, {t_ms}u, {freq_hz}u, "
        f"{array_name}, {len(raw)}u, {crc_present}, "
        f"{'true' if has_cmd else 'false'}, {hex(cmd) if has_cmd else 0}, "
        f"{'true' if has_flags else 'false'}, {start}, {end}, {oneway}, "
        f"{'true' if has_classification else 'false'}, {classification_expr}, "
        f"{'true' if has_hmac_valid else 'false'}, {hmac_valid}}},"
    )
    return array_decl, initializer


def slug_for(capture_id: str) -> str:
    return "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in capture_id)


def render_capture(capture: dict) -> "tuple[str, str]":
    """Returns (frame-array + byte-array declarations, CorpusCapture initializer)."""
    capture_id = capture["id"]
    slug = slug_for(capture_id)
    frames = capture["frames"]
    expect = capture.get("expect") or {}
    expect_frames = expect.get("frames") or []

    byte_decls = []
    frame_inits = []
    for index, frame in enumerate(frames):
        expect_frame = expect_frames[index] if index < len(expect_frames) else {}
        array_decl, initializer = render_frame(slug, index, frame, expect_frame)
        byte_decls.append(array_decl)
        frame_inits.append(initializer)

    frames_array_name = f"{slug}_frames"
    decls = "\n".join(byte_decls)
    decls += f"\ninline constexpr CorpusFrame {frames_array_name}[] = {{\n" + "\n".join(frame_inits) + "\n};"

    exchange = expect.get("exchange")
    has_exchange = "true" if exchange else "false"
    kind_expr = "ExchangeKind::NONE"
    outcome_expr = "ExchangeOutcome::NONE"
    if exchange:
        kind = exchange.get("kind")
        if kind not in EXCHANGE_KIND_ENUM:
            raise SystemExit(
                f"error: {capture_id}: expect.exchange.kind {kind!r} is not one of {sorted(EXCHANGE_KIND_ENUM)}"
            )
        kind_expr = EXCHANGE_KIND_ENUM[kind]
        outcome = exchange.get("outcome")
        if outcome not in EXCHANGE_OUTCOME_ENUM:
            raise SystemExit(
                f"error: {capture_id}: expect.exchange.outcome {outcome!r} is not one of {sorted(EXCHANGE_OUTCOME_ENUM)}"
            )
        outcome_expr = EXCHANGE_OUTCOME_ENUM[outcome]

    device = expect.get("device") or {}
    has_reported_position = "reported_position" in device
    reported_position = device.get("reported_position", 0)
    has_device_name = "name" in device
    device_name = device.get("name", "")

    oneway = expect.get("oneway") or {}
    has_oneway_intent = "intent" in oneway
    oneway_intent = oneway.get("intent", "")
    has_oneway_target_type = "target_type" in oneway
    oneway_target_type = oneway.get("target_type", 0)
    has_oneway_originator = "originator" in oneway
    oneway_originator = oneway.get("originator", 0)
    has_oneway_acei = "acei" in oneway
    oneway_acei = oneway.get("acei", 0)

    key_expr = KEY_MODE_ENUM[capture["key"]]
    origin_expr = c_string(capture["source"]["origin"])
    captured_with_expr = c_string(capture["source"]["captured_with"])

    capture_init = (
        f"  {{{c_string(capture_id)}, {origin_expr}, {captured_with_expr}, {key_expr}, "
        f"{has_exchange}, {kind_expr}, {outcome_expr}, "
        f"{frames_array_name}, {len(frames)}u, "
        f"{'true' if has_reported_position else 'false'}, {reported_position}u, "
        f"{'true' if has_device_name else 'false'}, {c_string(device_name)}, "
        f"{'true' if has_oneway_intent else 'false'}, {c_string(oneway_intent)}, "
        f"{'true' if has_oneway_target_type else 'false'}, {oneway_target_type}u, "
        f"{'true' if has_oneway_originator else 'false'}, {oneway_originator}u, "
        f"{'true' if has_oneway_acei else 'false'}, {oneway_acei}u}},"
    )
    return decls, capture_init


HEADER_PRELUDE = f"""{BANNER}
#pragma once

/// @file corpus_generated.h
/// @brief Generated golden-frame corpus fixtures. DO NOT EDIT — see scripts/corpus/build.py
/// and tests/corpus/README.md.

#include <cstddef>
#include <cstdint>

namespace esphome {{
namespace home_io_control {{
namespace corpus {{

enum class KeyMode : uint8_t {{ CORPUS, UNKNOWN }};
enum class ExchangeKind : uint8_t {{ NONE, DIRECT, AUTHENTICATED_COMMAND, PAIRING, ONEWAY, STATUS_POLL }};
enum class ExchangeOutcome : uint8_t {{ NONE, SUCCESS, TIMEOUT, FAILURE }};

/// @brief One captured wire frame plus optional per-frame expectations.
struct CorpusFrame {{
  bool tx;                    ///< true = controller->device (captured as `dir: tx`).
  bool has_t_ms;
  uint32_t t_ms;
  uint32_t freq_hz;           ///< 0 = unknown.
  const uint8_t *bytes;
  uint8_t len;                ///< Full wire bytes as captured (includes CRC when crc_present).
  bool crc_present;
  bool has_cmd;
  uint8_t cmd;
  bool has_flags;
  bool start;
  bool end;
  bool oneway;
  bool has_classification;
  uint8_t classification;     ///< Numeric value of a decisions:: enum.
  bool has_hmac_valid;
  bool hmac_valid;
}};

/// @brief One captured exchange/scenario: its frames plus optional capture-level expectations.
struct CorpusCapture {{
  const char *id;
  const char *source_origin;  ///< "own-hardware" | "github-issue" | "synthetic-bootstrap" | "reference-material".
  const char *captured_with;  ///< "sx1276" | "sx1262" | "other" | "synthetic" — radio chip.
  KeyMode key;
  bool has_exchange;
  ExchangeKind kind;
  ExchangeOutcome outcome;
  const CorpusFrame *frames;
  uint8_t frame_count;
  bool has_reported_position;
  uint8_t reported_position;
  bool has_device_name;
  const char *device_name;
  bool has_oneway_intent;
  const char *oneway_intent;
  bool has_oneway_target_type;
  uint16_t oneway_target_type;
  bool has_oneway_originator;
  uint8_t oneway_originator;
  bool has_oneway_acei;
  uint8_t oneway_acei;
}};
"""

HEADER_EPILOGUE = """
}  // namespace corpus
}  // namespace home_io_control
}  // namespace esphome
"""


def load_captures() -> list:
    paths = sorted(CAPTURES_DIR.rglob("*.yaml"))
    captures = []
    seen_ids = {}
    seen_slugs = {}
    for path in paths:
        with path.open(encoding="utf-8") as handle:
            data = yaml.safe_load(handle)
        capture_id = data["id"]
        if capture_id in seen_ids:
            raise SystemExit(f"error: duplicate capture id '{capture_id}' in {path} (already in {seen_ids[capture_id]})")
        seen_ids[capture_id] = path
        # Two distinct ids can slugify to the same C identifier (e.g. "a-b" and "a_b" both
        # become "a_b") — that's a colliding array/variable name, not just a duplicate id.
        slug = slug_for(capture_id)
        if slug in seen_slugs:
            other_id, other_path = seen_slugs[slug]
            raise SystemExit(
                f"error: capture id '{capture_id}' in {path} slugifies to '{slug}', colliding with "
                f"'{other_id}' in {other_path} — ids must be distinct after non-alphanumeric characters "
                "are replaced with '_'"
            )
        seen_slugs[slug] = (capture_id, path)
        captures.append(data)
    captures.sort(key=lambda c: c["id"])
    return captures


def render(captures: list) -> str:
    parts = [HEADER_PRELUDE]
    capture_inits = []
    for capture in captures:
        decls, init = render_capture(capture)
        parts.append("\n" + decls)
        capture_inits.append(init)

    parts.append("\ninline constexpr CorpusCapture CAPTURES[] = {\n" + "\n".join(capture_inits) + "\n};")
    parts.append("\ninline constexpr size_t CAPTURE_COUNT = sizeof(CAPTURES) / sizeof(CAPTURES[0]);")
    parts.append(HEADER_EPILOGUE)
    return "\n".join(parts)


def main() -> int:
    captures = load_captures()
    rendered = render(captures)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUTPUT_PATH.is_file() and OUTPUT_PATH.read_text(encoding="utf-8") == rendered:
        print(f"build.py: {OUTPUT_PATH} up to date ({len(captures)} captures)")
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"build.py: wrote {OUTPUT_PATH} ({len(captures)} captures)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
